/**
 * Scorm12Runtime
 *
 * Assembles the SCORM 1.2 runtime files shipped inside exported packages.
 *
 * Source files (under public/app/common/scorm/):
 * - scorm12/vendor/pipwerks/SCORM_API_wrapper.js — vendored upstream pipwerks
 *   wrapper (MIT, see THIRD-PARTY-NOTICES.md). Shipped byte-identical.
 * - scorm12/exe-scorm12-{client,policy,lifecycle,adapter}.js — project-owned
 *   runtime layers (AGPL-3.0-or-later).
 *
 * Package files (the two names are frozen by the runtime contract, see
 * doc/development/scorm12-runtime-contract.md — iDevices and the Moodle
 * plugin hard-code them):
 * - libs/SCORM_API_wrapper.js — the vendored wrapper, verbatim.
 * - libs/SCOFunctions.js — the five layers concatenated in load order
 *   (client, activities, policy, lifecycle, adapter), so the file stays
 *   self-contained for consumers that lazy-load exactly these two scripts.
 */

/** Vendored upstream pipwerks wrapper (relative to app/common/scorm/). */
export const SCORM12_VENDOR_WRAPPER_PATH = 'scorm12/vendor/pipwerks/SCORM_API_wrapper.js';

/** Project-owned runtime layers in load order (relative to app/common/scorm/). */
export const SCORM12_RUNTIME_LAYER_PATHS = [
    'scorm12/exe-scorm12-client.js',
    'scorm12/exe-scorm12-activities.js',
    'scorm12/exe-scorm12-policy.js',
    'scorm12/exe-scorm12-lifecycle.js',
    'scorm12/exe-scorm12-adapter.js',
] as const;

/** Every source file the SCORM 1.2 runtime assembly needs. */
export const SCORM12_RUNTIME_SOURCE_PATHS: readonly string[] = [
    SCORM12_VENDOR_WRAPPER_PATH,
    ...SCORM12_RUNTIME_LAYER_PATHS,
];

/**
 * Build the two runtime files shipped in a SCORM 1.2 package from the fetched
 * source files.
 *
 * @param sources - Map of source path (relative to app/common/scorm/) to
 * content, as returned by fetchScormFiles('1.2').
 * @returns Map of package-relative filename (under libs/) to content.
 * @throws Error naming every missing source file — a SCORM 1.2 export must
 * fail loudly rather than ship an incomplete runtime.
 */
export function buildScorm12RuntimeFiles(sources: Map<string, Uint8Array>): Map<string, Uint8Array | string> {
    const missing = SCORM12_RUNTIME_SOURCE_PATHS.filter(path => !sources.has(path));
    if (missing.length > 0) {
        throw new Error(`SCORM 1.2 runtime files are missing: ${missing.join(', ')}`);
    }

    const decoder = new TextDecoder();
    const sections = SCORM12_RUNTIME_LAYER_PATHS.map(path => {
        const name = path.split('/').pop();
        const text = decoder.decode(sources.get(path));
        return `/* ==== ${name} ==== */\n${text.trim()}\n`;
    });

    const banner =
        '/*\n' +
        ' * SCOFunctions.js — eXeLearning SCORM 1.2 runtime (assembled file).\n' +
        ' *\n' +
        ' * Generated by the SCORM 1.2 exporter from the AGPL-3.0-or-later source\n' +
        ' * layers in public/app/common/scorm/scorm12/ (see each section header\n' +
        ' * below for its license notice). Do not edit this file: edit the source\n' +
        ' * layers and re-export.\n' +
        ' *\n' +
        ' * SPDX-License-Identifier: AGPL-3.0-or-later\n' +
        ' */\n\n';

    const files = new Map<string, Uint8Array | string>();
    const wrapperBytes = sources.get(SCORM12_VENDOR_WRAPPER_PATH);
    if (wrapperBytes !== undefined) {
        files.set('SCORM_API_wrapper.js', wrapperBytes);
    }
    files.set('SCOFunctions.js', banner + sections.join('\n'));
    return files;
}
