#!/usr/bin/env bun
/**
 * Architecture record validation and index generation.
 *
 * Discovers Architecture Decision Records under `doc/architecture/adr/` and
 * change directories under `doc/architecture/changes/`, validates their
 * identifiers, metadata and cross-references, and generates the two indexes.
 *
 * Usage:
 *   bun run scripts/architecture-records.ts generate   # write the indexes
 *   bun run scripts/architecture-records.ts check      # validate, fail on drift
 *
 * The identification model is specified in
 * `doc/architecture/changes/2232-issue-based-architecture-identifiers/spec.md`
 * and decided in `doc/architecture/adr/ADR-2232-01-*.md`.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export const ADR_DIR = 'doc/architecture/adr';
export const CHANGES_DIR = 'doc/architecture/changes';
export const ADR_INDEX = `${ADR_DIR}/records.md`;
export const CHANGES_INDEX = `${CHANGES_DIR}/records.md`;
export const MIGRATION_MAP = 'doc/architecture/migration-map.md';

export const ADR_STATUSES = ['Proposed', 'Accepted', 'Rejected', 'Superseded'] as const;
export const CHANGE_STATUSES = ['draft', 'in-review', 'accepted', 'implemented', 'superseded', 'abandoned'] as const;

export const CHANGE_DOCUMENTS = ['proposal.md', 'spec.md', 'design.md', 'research.md', 'tasks.md'] as const;

export const ADR_FILENAME_RE = /^ADR-([1-9][0-9]*)-([0-9]{2})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/;
export const CHANGE_DIR_RE = /^([1-9][0-9]*)-([a-z0-9]+(?:-[a-z0-9]+)*)$/;
/**
 * A retired identifier is `ADR-NNNN` / `SDD-NNNN` that is *not* followed by a
 * two-digit local sequence — otherwise `ADR-1858-01` would match its own
 * `ADR-1858` prefix.
 */
export const LEGACY_ID_RE = /\b(?:ADR|SDD)-[0-9]{4}(?!-[0-9]{2})\b/;
export const LEGACY_FILENAME_RE = /^(?:ADR|SDD)-[0-9]{4}-/;

/**
 * Files allowed to mention legacy `ADR-NNNN` / `SDD-NNNN` identifiers, because
 * documenting the migration requires naming what was migrated. Everything else
 * in the repository must use current identifiers.
 */
export const LEGACY_REFERENCE_ALLOWLIST = [
    MIGRATION_MAP,
    `${ADR_DIR}/ADR-2232-01-use-tracking-issue-based-architecture-identifiers.md`,
    `${CHANGES_DIR}/2232-issue-based-architecture-identifiers/`,
];

const GENERATED_BANNER =
    '<!-- Generated by `bun run scripts/architecture-records.ts generate`. Do not edit by hand. -->';

// ---------------------------------------------------------------------------
// Minimal frontmatter parser
// ---------------------------------------------------------------------------

export type YamlValue = string | number | YamlValue[] | { [key: string]: YamlValue };

/**
 * Parses the bounded YAML subset used by architecture frontmatter:
 * scalars, inline lists, block lists, and one level of nested mappings.
 * Deliberately not a general YAML parser — the schema is fixed and small,
 * and a full YAML dependency is not warranted for it.
 */
export function parseFrontmatter(raw: string): { data: Record<string, YamlValue>; body: string } | null {
    const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!match) return null;

    const data: Record<string, YamlValue> = {};
    const lines = match[1].split(/\r?\n/);

    let currentKey: string | null = null;
    let currentList: string[] | null = null;
    let currentMap: Record<string, YamlValue> | null = null;

    const flush = (): void => {
        if (currentKey === null) return;
        if (currentList !== null) data[currentKey] = currentList;
        else if (currentMap !== null) data[currentKey] = currentMap;
        currentList = null;
        currentMap = null;
        currentKey = null;
    };

    for (const line of lines) {
        if (line.trim() === '' || line.trim().startsWith('#')) continue;

        const topLevel = line.match(/^([A-Za-z_][A-Za-z0-9_]*):(.*)$/);
        if (topLevel) {
            flush();
            const key = topLevel[1];
            const rest = topLevel[2].trim();
            if (rest === '') {
                currentKey = key;
            } else {
                data[key] = parseScalarOrInlineList(rest);
            }
            continue;
        }

        const listItem = line.match(/^\s+-\s*(.*)$/);
        if (listItem && currentKey !== null) {
            currentMap = null;
            currentList ??= [];
            currentList.push(stripQuotes(listItem[1].trim()));
            continue;
        }

        const nested = line.match(/^\s+([A-Za-z_][A-Za-z0-9_]*):(.*)$/);
        if (nested && currentKey !== null) {
            currentList = null;
            currentMap ??= {};
            currentMap[nested[1]] = parseScalarOrInlineList(nested[2].trim());
        }
    }
    flush();

    return { data, body: match[2] };
}

function stripQuotes(value: string): string {
    return value.replace(/^["'](.*)["']$/, '$1');
}

function parseScalarOrInlineList(raw: string): YamlValue {
    if (raw.startsWith('[') && raw.endsWith(']')) {
        const inner = raw.slice(1, -1).trim();
        if (inner === '') return [];
        return inner.split(',').map(part => stripQuotes(part.trim()));
    }
    return stripQuotes(raw);
}

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

export type Adr = {
    path: string;
    file: string;
    id: string;
    issue: number;
    sequence: string;
    title: string;
    status: string;
    date: string;
    trackingIssue: string;
    legacyId: string | null;
    supersedes: string[];
    supersededBy: string[];
    relatedAdrs: string[];
    relatedChanges: string[];
    relatedPrs: string[];
    deciders: string[];
    aiTool: string | null;
    aiModel: string | null;
    h1: string | null;
};

export type ChangeDoc = {
    path: string;
    name: string;
    data: Record<string, YamlValue>;
};

export type Change = {
    dir: string;
    name: string;
    issue: number;
    slug: string;
    documents: ChangeDoc[];
    canonical: ChangeDoc | null;
    title: string;
    status: string;
    date: string;
    implementationPrs: string[];
    relatedAdrs: string[];
    legacyId: string | null;
};

export type Diagnostic = { file: string; message: string };

function asList(value: YamlValue | undefined): string[] {
    if (value === undefined) return [];
    if (Array.isArray(value)) return value.map(String);
    if (typeof value === 'object') return [];
    const single = String(value).trim();
    return single === '' ? [] : [single];
}

function asString(value: YamlValue | undefined): string {
    if (value === undefined) return '';
    if (typeof value === 'object') return '';
    return String(value);
}

function nested(data: Record<string, YamlValue>, key: string, sub: string): YamlValue | undefined {
    const node = data[key];
    if (node && typeof node === 'object' && !Array.isArray(node)) return node[sub];
    return undefined;
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

export function discoverAdrs(root: string): { adrs: Adr[]; errors: Diagnostic[] } {
    const dir = join(root, ADR_DIR);
    const adrs: Adr[] = [];
    const errors: Diagnostic[] = [];
    if (!existsSync(dir)) return { adrs, errors };

    for (const file of readdirSync(dir).sort()) {
        if (!file.endsWith('.md')) continue;
        if (file === 'README.md' || file === 'records.md' || file === 'template.md') continue;

        const rel = `${ADR_DIR}/${file}`;

        // The new grammar is checked first: `ADR-1858-01-slug.md` also starts with
        // four digits, so the legacy pattern would otherwise shadow it.
        const match = file.match(ADR_FILENAME_RE);
        if (!match) {
            errors.push({
                file: rel,
                message: LEGACY_FILENAME_RE.test(file)
                    ? 'uses the retired global numbering. Rename to ADR-<issue>-<NN>-<decision-slug>.md ' +
                      '(see doc/architecture/adr/README.md).'
                    : 'filename does not match ADR-<issue>-<NN>-<decision-slug>.md',
            });
            continue;
        }

        const parsed = parseFrontmatter(readFileSync(join(dir, file), 'utf8'));
        if (!parsed) {
            errors.push({ file: rel, message: 'missing YAML frontmatter' });
            continue;
        }

        const { data, body } = parsed;
        const h1 = body.match(/^# (.+)$/m)?.[1] ?? null;

        adrs.push({
            path: rel,
            file,
            id: asString(data.id),
            issue: Number(match[1]),
            sequence: match[2],
            title: asString(data.title),
            status: asString(data.status),
            date: asString(data.date),
            trackingIssue: asString(data.tracking_issue),
            legacyId: data.legacy_id !== undefined ? asString(data.legacy_id) : null,
            supersedes: asList(data.supersedes),
            supersededBy: asList(data.superseded_by),
            relatedAdrs: asList(nested(data, 'related', 'adrs')),
            relatedChanges: asList(nested(data, 'related', 'changes')),
            relatedPrs: asList(nested(data, 'related', 'prs')),
            deciders: asList(data.deciders),
            aiTool: data.ai_assistance !== undefined ? asString(nested(data, 'ai_assistance', 'tool')) : null,
            aiModel: data.ai_assistance !== undefined ? asString(nested(data, 'ai_assistance', 'model')) : null,
            h1,
        });
    }

    return { adrs, errors };
}

export function discoverChanges(root: string): { changes: Change[]; errors: Diagnostic[] } {
    const dir = join(root, CHANGES_DIR);
    const changes: Change[] = [];
    const errors: Diagnostic[] = [];
    if (!existsSync(dir)) return { changes, errors };

    for (const entry of readdirSync(dir).sort()) {
        const full = join(dir, entry);
        if (!statSync(full).isDirectory()) continue;

        const rel = `${CHANGES_DIR}/${entry}`;
        const match = entry.match(CHANGE_DIR_RE);
        if (!match) {
            errors.push({ file: rel, message: 'directory name does not match <issue>-<change-slug>' });
            continue;
        }

        const documents: ChangeDoc[] = [];
        for (const name of CHANGE_DOCUMENTS) {
            const docPath = join(full, name);
            if (!existsSync(docPath)) continue;
            const parsed = parseFrontmatter(readFileSync(docPath, 'utf8'));
            if (!parsed) {
                errors.push({ file: `${rel}/${name}`, message: 'missing YAML frontmatter' });
                continue;
            }
            documents.push({ path: `${rel}/${name}`, name, data: parsed.data });
        }

        if (documents.length === 0) {
            errors.push({
                file: rel,
                message: `contains no recognised document (${CHANGE_DOCUMENTS.join(', ')})`,
            });
            continue;
        }

        const canonical = documents[0];
        changes.push({
            dir: rel,
            name: entry,
            issue: Number(match[1]),
            slug: match[2],
            documents,
            canonical,
            title: asString(canonical.data.title),
            status: asString(canonical.data.status),
            date: asString(canonical.data.date),
            implementationPrs: asList(canonical.data.implementation_prs),
            relatedAdrs: asList(canonical.data.related_adrs),
            legacyId: canonical.data.legacy_id !== undefined ? asString(canonical.data.legacy_id) : null,
        });
    }

    return { changes, errors };
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export function isValidDate(value: string): boolean {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
    const [year, month, day] = value.split('-').map(Number);
    const date = new Date(Date.UTC(year, month - 1, day));
    return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day;
}

export function isPositiveInteger(value: string): boolean {
    return /^[1-9][0-9]*$/.test(value);
}

export function validate(adrs: Adr[], changes: Change[]): Diagnostic[] {
    const problems: Diagnostic[] = [];
    const add = (file: string, message: string): void => {
        problems.push({ file, message });
    };

    const adrIds = new Set(adrs.map(a => a.id));
    const changeNames = new Set(changes.map(c => c.name));
    const seenIds = new Map<string, string>();
    const seenSequences = new Map<string, string>();

    for (const adr of adrs) {
        const expectedId = `ADR-${adr.issue}-${adr.sequence}`;

        if (adr.id === '') add(adr.path, 'missing required field `id`');
        else if (adr.id !== expectedId) {
            add(adr.path, `frontmatter id "${adr.id}" does not match filename (expected "${expectedId}")`);
        }

        if (adr.title === '') add(adr.path, 'missing required field `title`');
        if (adr.date === '') add(adr.path, 'missing required field `date`');
        else if (!isValidDate(adr.date)) add(adr.path, `date "${adr.date}" is not a valid YYYY-MM-DD date`);

        if (adr.status === '') add(adr.path, 'missing required field `status`');
        else if (!(ADR_STATUSES as readonly string[]).includes(adr.status)) {
            add(adr.path, `status "${adr.status}" is not one of ${ADR_STATUSES.join(', ')}`);
        }

        if (adr.trackingIssue === '') add(adr.path, 'missing required field `tracking_issue`');
        else if (!isPositiveInteger(adr.trackingIssue)) {
            add(adr.path, `tracking_issue "${adr.trackingIssue}" is not a positive integer`);
        } else if (Number(adr.trackingIssue) !== adr.issue) {
            add(adr.path, `tracking_issue ${adr.trackingIssue} does not match filename issue ${adr.issue}`);
        }

        if (adr.deciders.length === 0) add(adr.path, 'missing required field `deciders`');
        if (adr.aiTool === null || adr.aiTool === '') {
            add(adr.path, 'missing required field `ai_assistance.tool` (use `none` if no AI tool was used)');
        }
        if (adr.aiModel === null || adr.aiModel === '') {
            add(adr.path, 'missing required field `ai_assistance.model` (use `none` if no AI tool was used)');
        }

        const expectedH1 = `${expectedId}: ${adr.title}`;
        if (adr.h1 === null) add(adr.path, 'missing H1 heading');
        else if (adr.h1 !== expectedH1) add(adr.path, `H1 is "${adr.h1}" but should be "${expectedH1}"`);

        const previousId = seenIds.get(adr.id);
        if (previousId !== undefined) add(adr.path, `duplicate ADR id "${adr.id}" (also in ${previousId})`);
        else if (adr.id !== '') seenIds.set(adr.id, adr.path);

        const sequenceKey = `${adr.issue}-${adr.sequence}`;
        const previousSequence = seenSequences.get(sequenceKey);
        if (previousSequence !== undefined) {
            add(
                adr.path,
                `duplicate local sequence ${adr.sequence} for issue ${adr.issue} (also in ${previousSequence})`,
            );
        } else seenSequences.set(sequenceKey, adr.path);

        for (const ref of adr.relatedAdrs) {
            if (!adrIds.has(ref)) add(adr.path, `related.adrs references unknown ADR "${ref}"`);
        }
        for (const ref of adr.relatedChanges) {
            if (!changeNames.has(ref)) add(adr.path, `related.changes references unknown change "${ref}"`);
        }
        for (const pr of adr.relatedPrs) {
            if (!isPositiveInteger(pr)) add(adr.path, `related.prs value "${pr}" is not a positive integer`);
        }

        for (const ref of adr.supersedes) {
            if (ref === adr.id) add(adr.path, 'ADR cannot supersede itself');
            else if (!adrIds.has(ref)) add(adr.path, `supersedes references unknown ADR "${ref}"`);
            else {
                const target = adrs.find(a => a.id === ref);
                if (target && !target.supersededBy.includes(adr.id)) {
                    add(adr.path, `supersedes "${ref}" but ${target.path} does not list superseded_by: [${adr.id}]`);
                }
                if (target && target.status !== 'Superseded') {
                    add(target.path, `is superseded by ${adr.id} but status is "${target.status}", not "Superseded"`);
                }
            }
        }
        for (const ref of adr.supersededBy) {
            if (ref === adr.id) add(adr.path, 'ADR cannot be superseded by itself');
            else if (!adrIds.has(ref)) add(adr.path, `superseded_by references unknown ADR "${ref}"`);
            else {
                const target = adrs.find(a => a.id === ref);
                if (target && !target.supersedes.includes(adr.id)) {
                    add(adr.path, `superseded_by "${ref}" but ${target.path} does not list supersedes: [${adr.id}]`);
                }
            }
        }
    }

    for (const change of changes) {
        const canonical = change.canonical;
        if (canonical === null) continue;

        if (change.title === '') add(canonical.path, 'missing required field `title`');
        if (change.date === '') add(canonical.path, 'missing required field `date`');
        else if (!isValidDate(change.date)) {
            add(canonical.path, `date "${change.date}" is not a valid YYYY-MM-DD date`);
        }

        if (change.status === '') add(canonical.path, 'missing required field `status`');
        else if (!(CHANGE_STATUSES as readonly string[]).includes(change.status)) {
            add(canonical.path, `status "${change.status}" is not one of ${CHANGE_STATUSES.join(', ')}`);
        }

        for (const pr of change.implementationPrs) {
            if (!isPositiveInteger(pr)) {
                add(canonical.path, `implementation_prs value "${pr}" is not a positive integer`);
            }
        }
        for (const ref of change.relatedAdrs) {
            if (!adrIds.has(ref)) add(canonical.path, `related_adrs references unknown ADR "${ref}"`);
        }

        for (const doc of change.documents) {
            const issue = asString(doc.data.tracking_issue);
            if (issue === '') add(doc.path, 'missing required field `tracking_issue`');
            else if (!isPositiveInteger(issue)) {
                add(doc.path, `tracking_issue "${issue}" is not a positive integer`);
            } else if (Number(issue) !== change.issue) {
                add(doc.path, `tracking_issue ${issue} does not match change directory issue ${change.issue}`);
            }

            if (asString(doc.data.title) === '') add(doc.path, 'missing required field `title`');

            for (const pr of asList(doc.data.related_prs)) {
                if (!isPositiveInteger(pr)) add(doc.path, `related_prs value "${pr}" is not a positive integer`);
            }

            if (doc !== canonical && doc.data.implementation_prs !== undefined) {
                add(
                    doc.path,
                    `declares implementation_prs, but ${canonical.name} is the canonical metadata carrier for this change`,
                );
            }
        }
    }

    return problems;
}

/** Scans tracked files for retired identifiers outside the documented allowlist. */
export function findLegacyReferences(root: string, files: string[]): Diagnostic[] {
    const problems: Diagnostic[] = [];
    for (const file of files) {
        if (LEGACY_REFERENCE_ALLOWLIST.some(allowed => file === allowed || file.startsWith(allowed))) {
            continue;
        }
        const full = join(root, file);
        if (!existsSync(full)) continue;

        let content: string;
        try {
            content = readFileSync(full, 'utf8');
        } catch {
            continue;
        }
        if (content.includes('\0')) continue;

        // A migrated document may name its own former identifier, so that the
        // provenance note in the document itself stays readable.
        const ownLegacyId = file.endsWith('.md')
            ? (parseFrontmatter(content)?.data.legacy_id as string | undefined)
            : undefined;

        content.split(/\r?\n/).forEach((line, index) => {
            if (line.includes('legacy_id:')) return;
            const hit = line.match(LEGACY_ID_RE);
            if (hit && ownLegacyId !== undefined && hit[0] === ownLegacyId) return;
            if (hit) {
                problems.push({
                    file: `${file}:${index + 1}`,
                    message: `references retired identifier "${hit[0]}". Use the current identifier (see ${MIGRATION_MAP}).`,
                });
            }
        });
    }
    return problems;
}

// ---------------------------------------------------------------------------
// Index generation
// ---------------------------------------------------------------------------

export function sortAdrs(adrs: Adr[]): Adr[] {
    return [...adrs].sort((a, b) => a.issue - b.issue || a.sequence.localeCompare(b.sequence));
}

export function sortChanges(changes: Change[]): Change[] {
    return [...changes].sort((a, b) => a.issue - b.issue || a.slug.localeCompare(b.slug));
}

function issueLink(issue: number): string {
    return `[#${issue}](https://github.com/exelearning/exelearning/issues/${issue})`;
}

export function renderAdrIndex(adrs: Adr[]): string {
    const sorted = sortAdrs(adrs);
    const lines: string[] = [
        GENERATED_BANNER,
        '',
        '# ADR Index',
        '',
        'Architecture Decision Records for the main eXeLearning repository, ordered by',
        'tracking issue and then by local sequence. See [Architecture Decision Records](README.md)',
        'for the policy and [`template.md`](template.md) for the starting point.',
        '',
        '| ID | Title | Status | Issue | Date |',
        '|---|---|---|---|---|',
    ];

    for (const adr of sorted) {
        lines.push(
            `| [${adr.id}](${adr.file}) | ${adr.title} | ${adr.status} | ${issueLink(adr.issue)} | ${adr.date} |`,
        );
    }

    for (const status of ADR_STATUSES) {
        lines.push('', `## ${status}`, '');
        const group = sorted.filter(adr => adr.status === status);
        if (group.length === 0) {
            lines.push(`_No ${status.toLowerCase()} ADRs._`);
            continue;
        }
        for (const adr of group) {
            const supersession = adr.supersededBy.length > 0 ? ` — superseded by ${adr.supersededBy.join(', ')}` : '';
            lines.push(`- [${adr.id}](${adr.file}) — ${adr.title}${supersession}`);
        }
    }

    return `${lines.join('\n')}\n`;
}

export function renderChangeIndex(changes: Change[]): string {
    const sorted = sortChanges(changes);
    const lines: string[] = [
        GENERATED_BANNER,
        '',
        '# Change Index',
        '',
        'Change proposals, specifications and designs for the main eXeLearning repository,',
        'ordered by tracking issue. Each change lives in its own directory named',
        '`<issue>-<change-slug>`. See [Architecture changes](README.md) for the policy.',
        '',
        '| Change | Title | Status | Issue | Date | Documents |',
        '|---|---|---|---|---|---|',
    ];

    for (const change of sorted) {
        const docs = change.documents
            .map(doc => `[${doc.name.replace(/\.md$/, '')}](${change.name}/${doc.name})`)
            .join(', ');
        lines.push(
            `| \`${change.name}\` | ${change.title} | ${change.status} | ${issueLink(change.issue)} | ${change.date} | ${docs} |`,
        );
    }

    for (const status of CHANGE_STATUSES) {
        lines.push('', `## ${status}`, '');
        const group = sorted.filter(change => change.status === status);
        if (group.length === 0) {
            lines.push(`_No ${status} changes._`);
            continue;
        }
        for (const change of group) {
            const adrs = change.relatedAdrs.length > 0 ? ` — ${change.relatedAdrs.join(', ')}` : '';
            lines.push(`- [\`${change.name}\`](${change.name}/${change.documents[0].name}) — ${change.title}${adrs}`);
        }
    }

    return `${lines.join('\n')}\n`;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function trackedFiles(root: string): string[] {
    const result = Bun.spawnSync(['git', 'ls-files'], { cwd: root });
    if (result.exitCode !== 0) return [];
    return result.stdout.toString().split('\n').filter(Boolean);
}

function report(title: string, problems: Diagnostic[]): void {
    if (problems.length === 0) return;
    console.error(`\n${title}`);
    for (const problem of problems) console.error(`  ✗ ${problem.file}: ${problem.message}`);
}

export function run(mode: 'generate' | 'check', root: string): number {
    const { adrs, errors: adrErrors } = discoverAdrs(root);
    const { changes, errors: changeErrors } = discoverChanges(root);
    const structural = [...adrErrors, ...changeErrors];
    const metadata = validate(adrs, changes);
    const legacy = findLegacyReferences(root, trackedFiles(root));

    const adrIndex = renderAdrIndex(adrs);
    const changeIndex = renderChangeIndex(changes);

    if (mode === 'generate') {
        report('Structural problems:', structural);
        report('Metadata problems:', metadata);
        if (structural.length > 0) {
            console.error('\nRefusing to generate indexes while structural problems remain.');
            return 1;
        }
        writeFileSync(join(root, ADR_INDEX), adrIndex);
        writeFileSync(join(root, CHANGES_INDEX), changeIndex);
        console.log(`Wrote ${ADR_INDEX} (${adrs.length} ADRs)`);
        console.log(`Wrote ${CHANGES_INDEX} (${changes.length} changes)`);
        return metadata.length > 0 ? 1 : 0;
    }

    const drift: Diagnostic[] = [];
    const committedAdrIndex = existsSync(join(root, ADR_INDEX)) ? readFileSync(join(root, ADR_INDEX), 'utf8') : null;
    const committedChangeIndex = existsSync(join(root, CHANGES_INDEX))
        ? readFileSync(join(root, CHANGES_INDEX), 'utf8')
        : null;

    if (committedAdrIndex !== adrIndex) {
        drift.push({
            file: ADR_INDEX,
            message: 'differs from the generated index. Run `make architecture-records`.',
        });
    }
    if (committedChangeIndex !== changeIndex) {
        drift.push({
            file: CHANGES_INDEX,
            message: 'differs from the generated index. Run `make architecture-records`.',
        });
    }

    report('Structural problems:', structural);
    report('Metadata problems:', metadata);
    report('Retired identifier references:', legacy);
    report('Index drift:', drift);

    const total = structural.length + metadata.length + legacy.length + drift.length;
    if (total === 0) {
        console.log(`Architecture records OK — ${adrs.length} ADRs, ${changes.length} changes.`);
        return 0;
    }
    console.error(`\n${total} problem(s) found.`);
    return 1;
}

if (import.meta.main) {
    const mode = process.argv[2];
    if (mode !== 'generate' && mode !== 'check') {
        console.error('Usage: bun run scripts/architecture-records.ts <generate|check>');
        process.exit(2);
    }
    process.exit(run(mode, process.cwd()));
}
